/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-Text-Input-Service.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Text Input Service
 #	author : miyako
 #	2023/08/07
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-Text-Input-Service.h"

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
			// --- Text Input Service
            
			case 1 :
                PA_RunInMainProcess((PA_RunInMainProcessProcPtr)INPUT_SET_SOURCE, params);
				break;
			case 2 :
                PA_RunInMainProcess((PA_RunInMainProcessProcPtr)INPUT_Get_source, params);
				break;
			case 3 :
                INPUT_SOURCE_LIST(params);
				break;

        }

	}
	catch(...)
	{

	}
}

#pragma mark -

void INPUT_SET_SOURCE(PA_PluginParameters params) {

    PackagePtr pParams = (PackagePtr)params->fParameters;
    C_TEXT Param1;
    Param1.fromParamAtIndex(pParams, 1);
    
    TISInputSourceRef source = nil;
    
    if(Param1.getUTF16Length() == 0){
        source = TISCopyCurrentASCIICapableKeyboardInputSource();
    }else{
        NSString *language = Param1.copyUTF16String();
        if(language != nil){
            if([language isEqualToString:@"ASCII"]){
                source = TISCopyCurrentASCIICapableKeyboardInputSource();
            }else{
                CFArrayRef sources = TISCreateInputSourceList(NULL, NO);
                if(sources)
                {
                    CFIndex i, count = CFArrayGetCount(sources);
                    TISInputSourceRef s;
                    for (i = 0; i < count; ++i)
                    {
                        s = (TISInputSourceRef)CFArrayGetValueAtIndex(sources, i);
                        if(s != nil)
                        {
                            CFStringRef sourceID = (CFStringRef)TISGetInputSourceProperty(s, kTISPropertyInputSourceID);
                            /* sourceID is not guaranteed to be present for every input source;
                               skip rather than pass NULL into CFStringCompare (undefined behavior) */
                            if(sourceID != NULL &&
                               CFStringCompare((CFStringRef)language, sourceID, 0) == kCFCompareEqualTo)
                            {
                                source = (TISInputSourceRef)CFRetain(s);
                                break;
                            }
                        }
                    }
                    CFRelease(sources);
                }
                if(source == nil)
                {
                    source = TISCopyInputSourceForLanguage((CFStringRef)language);
                }
            }
            [language release];
        }
    }
    
    if(source) {
        /*
         *      If there is more than one such input source
         *      and at least one has previously been used, then the
         *      most-recently-used one will be chosen
         */
        TISSelectInputSource(source);
        CFRelease(source);
    }
}

void INPUT_Get_source(PA_PluginParameters params) {
    
    PackagePtr pParams = (PackagePtr)params->fParameters;
    sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
    C_TEXT Param1, returnValue;
    Param1.fromParamAtIndex(pParams, 1);
    
    TISInputSourceRef source = nil;

    if(Param1.getUTF16Length() == 0){
        source = TISCopyCurrentKeyboardInputSource();
    }else{
        NSString *language = Param1.copyUTF16String();
        
        if(language != nil){
            if([language isEqualToString:@"ASCII"]){
                source = TISCopyCurrentASCIICapableKeyboardInputSource();
            }else{
                source = TISCopyInputSourceForLanguage((CFStringRef)language);
            }
            
            [language release];
        }
    }
    
    if(source) {
        NSString *identifier = (NSString *)TISGetInputSourceProperty(source, kTISPropertyInputSourceID);
        returnValue.setUTF16String(identifier);
        CFRelease(source);
    }
    
    returnValue.setReturn(pResult);
}

/*
 * Converts an NSImage to a base64-encoded TIFF string, without leaking memory.
 * Returns nil if the image has no valid raster representation (e.g. a 0-size
 * image, or a vector-only representation that fails to rasterize) rather than
 * risk passing a NULL CGImageRef into CGImageDestinationAddImage.
 */
static NSString *_base64TIFFFromNSImage(NSImage *icon) {

    if(icon == nil) return nil;

    NSRect imageRect = NSMakeRect(0, 0, icon.size.width, icon.size.height);
    CGImageRef image = [icon CGImageForProposedRect:(NSRect *)&imageRect context:NULL hints:NULL];
    if(image == NULL) return nil; /* nothing to encode; avoid feeding NULL to CGImageDestinationAddImage */

    NSString *result = nil;
    CFMutableDataRef data = CFDataCreateMutable(kCFAllocatorDefault, 0);
    CGImageDestinationRef destination = CGImageDestinationCreateWithData(data, kUTTypeTIFF, 1, NULL);
    if(destination != NULL)
    {
        CFMutableDictionaryRef properties = CFDictionaryCreateMutable(kCFAllocatorDefault, 0, NULL, NULL);
        CGImageDestinationAddImage(destination, image, properties);
        CGImageDestinationFinalize(destination);
        result = [(NSData *)data base64EncodedStringWithOptions:0];
        CFRelease(properties);
        CFRelease(destination);
    }
    CFRelease(data);

    return result;
}

static void _input_sources_list(NSMutableArray *list) {
 
    CFArrayRef sources = TISCreateInputSourceList(NULL, NO);
    if(sources)
    {
        CFIndex i, count = CFArrayGetCount(sources);
        TISInputSourceRef s;
        for (i = 0; i < count; ++i)
        {
            s = (TISInputSourceRef)CFArrayGetValueAtIndex(sources, i);
            if(s != nil)
            {
                NSMutableDictionary *dict = [[NSMutableDictionary alloc]init];
                
                NSString *category = (NSString *)TISGetInputSourceProperty(s, kTISPropertyInputSourceCategory);
                if(category != nil) [dict setObject:category forKey:@"category"];

                NSString *name = (NSString *)TISGetInputSourceProperty(s, kTISPropertyLocalizedName);
                if(name != nil) [dict setObject:name forKey:@"name"];
                
                NSString *type = (NSString *)TISGetInputSourceProperty(s, kTISPropertyInputSourceType);
                if(type != nil) [dict setObject:type forKey:@"type"];
                                
                NSString *inputSourceID = (NSString *)TISGetInputSourceProperty(s, kTISPropertyInputSourceID);
                if(inputSourceID != nil) [dict setObject:inputSourceID forKey:@"inputSourceID"];
                
                NSString *bundleID = (NSString *)TISGetInputSourceProperty(s, kTISPropertyBundleID);
                if(bundleID != nil) [dict setObject:bundleID forKey:@"bundleID"];
                                
                NSString *inputModeID = (NSString *)TISGetInputSourceProperty(s, kTISPropertyInputModeID);
                if(inputModeID != nil) [dict setObject:inputModeID forKey:@"inputModeID"];
                                
                NSImage *icon;
                
                NSURL *url = (NSURL *)TISGetInputSourceProperty(s, kTISPropertyIconImageURL);
                if(url)
                {
                    /*
                     * NOTE: this reads the icon resource from disk synchronously, on the
                     * main process (this function is invoked via PA_RunInMainProcess).
                     * A slow or unreachable volume here will stall the whole 4D UI,
                     * once per input source enumerated. Consider prefetching/caching
                     * icons off the main thread if this becomes a noticeable freeze.
                     */
                    icon = [[NSImage alloc]initWithContentsOfURL:url];
                    
                    if(!icon){
                        //the extension is sometimes wrong; try again png -> tiff
                        url = [url.URLByDeletingPathExtension URLByAppendingPathExtension:@"tiff"];
                        icon = [[NSImage alloc]initWithContentsOfURL:url];
                    }
                    
                    if(icon){
                        NSString *base64 = _base64TIFFFromNSImage(icon);
                        if(base64 != nil) [dict setObject:base64 forKey:@"icon"];
                        [icon release];
                    }
                         
                }else{
                    IconRef iconRef = (IconRef)TISGetInputSourceProperty(s, kTISPropertyIconRef);
                    if(iconRef){
                        NSImage *icon = [[NSImage alloc]initWithIconRef:iconRef];
                        NSString *base64 = _base64TIFFFromNSImage(icon);
                        if(base64 != nil) [dict setObject:base64 forKey:@"icon"];
                        [icon release];
                    }
                }

                [list addObject:dict];
                [dict release];
            }
        }
        CFRelease(sources);
    }
}

void INPUT_SOURCE_LIST(PA_PluginParameters params) {

    PA_CollectionRef ss = PA_CreateCollection();
    
    NSMutableArray *list = [[NSMutableArray alloc]init];
    
    PA_RunInMainProcess((PA_RunInMainProcessProcPtr)_input_sources_list, list);
    
    for(CFIndex i = 0; i < [list count]; ++i) {
        
        PA_ObjectRef o = PA_CreateObject();
        
        NSDictionary *dict = [list objectAtIndex:i];
        NSString *category = [dict objectForKey:@"category"];
        if(category != nil) ob_set_s(o, "category", [category UTF8String]);
        
        NSString *name = [dict objectForKey:@"name"];
        if(name != nil) ob_set_s(o, "name", [name UTF8String]);
        
        NSString *type = [dict objectForKey:@"type"];
        if(type != nil) ob_set_s(o, "type", [type UTF8String]);
        
        NSString *inputSourceID = [dict objectForKey:@"inputSourceID"];
        if(inputSourceID != nil) ob_set_s(o, "inputSourceID", [inputSourceID UTF8String]);
        
        NSString *bundleID = [dict objectForKey:@"bundleID"];
        if(bundleID != nil) ob_set_s(o, "bundleID", [bundleID UTF8String]);
        
        NSString *inputModeID = [dict objectForKey:@"inputModeID"];
        if(inputModeID != nil) ob_set_s(o, "inputModeID", [inputModeID UTF8String]);

        NSString *icon = [dict objectForKey:@"icon"];
        if(icon != nil) {
            NSData *data = [[NSData alloc]initWithBase64EncodedString:icon options:0];
            PA_Picture p = PA_CreatePicture((void *)[data bytes], (PA_long32)[data length]);
            ob_set_p(o, L"icon", p);
            [data release];
        }
        
        PA_Variable v = PA_CreateVariable(eVK_Object);
        PA_SetObjectVariable(&v, o);
        PA_SetCollectionElement(ss, PA_GetCollectionLength(ss), v);
        PA_ClearVariable(&v);
    }
    
    [list release];
    
    PA_ReturnCollection(params, ss);
}

