/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Text-Input-Service.h
 #	source generated by 4D Plugin Wizard
 #	Project : Text Input Service
 #	author : miyako
 #	2023/08/07
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_TEXT_INPUT_SERVICE_H
#define PLUGIN_TEXT_INPUT_SERVICE_H

#include "4DPluginAPI.h"
#include "C_TEXT.h"
#include "4DPlugin-JSON.h"
#import <Carbon/Carbon.h>

#pragma mark -

void INPUT_SET_SOURCE(PA_PluginParameters params);
void INPUT_Get_source(PA_PluginParameters params);
void INPUT_SOURCE_LIST(PA_PluginParameters params);

#endif /* PLUGIN_TEXT_INPUT_SERVICE_H */
